### ISSUE TITLE
Allow preferred JS package managers instead of yarn

### ISSUE THREAD

**Issue by park-jemin** [mattbrictson/nextgen#118]
Really enjoyed using this so far, but one downside for me is the lack of configurability for the package manager. Would be awesome if we could get this incorporated into the project given the high configurability in other areas

Related issue: https://github.com/rails/jsbundling-rails/issues/176

**Comment by mattbrictson** [comment]
Thanks for the suggestion! My understanding is that `rails new` is still hard-coded to Yarn in most cases. E.g. if you run `rails new --javascript=esbuild`, Rails will use Yarn no matter what:

https://github.com/rails/jsbundling-rails/blob/5fc0b109aee34ac2ae6334c552e223ff303e9f12/lib/install/esbuild/install.rb#L5

Therefore, to implement a choice of package manager, nextgen will need to run `rails new`, then retroactively delete the generated `yarn.lock` and re-install with the user's package manager of choice.

It sounds like this might be better handled upstream in jsbundling-rails, but the issue you linked has been dormant for almost a year, so I guess that's not a high priority for the project.

Anyway, just checking that I've assessed the situation correctly. Does that sound right?

Also, if nextgen were to add just one additional package manager to start (i.e. besides Yarn), which do you think would be most valuable? NPM? This wouldn't preclude adding more packages managers later, but I'd like to start simple.

**Comment by mattbrictson** [comment]
Looking into it some more, there are some non-obvious places where yarn is hardcoded by Rails:

- Procfile.dev
- Dockerfile

So we will need to retroactively munge these files as well after running `rails new`.

**Comment by mattbrictson** [comment]
I've implemented an npm option in #122.

I also looked into pnpm support, but it seemed a little more complicated. The default GitHub Actions runner, for example, doesn't have pnpm out of the box, we should need to insert an extra `pnpm/action-setup` step in the CI workflow that Rails provides.

I decided to add just npm for now.
